# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rznotifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='covered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='investments_count',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='purpose',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='questions_count',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining_investment',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='story',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='term_in_months',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='topped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
