# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rznotifier', '0002_auto_20160619_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
