# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rznotifier', '0003_loan_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='main_income_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='region',
            field=models.SmallIntegerField(null=True),
        ),
    ]
