# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rznotifier', '0004_auto_20160619_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='topped',
            field=models.NullBooleanField(),
        ),
    ]
